add_rules("mode.debug", "mode.release")
add_rules("plugin.vsxmake.autoupdate")

target("GalaxyMath")
    set_languages("c++20")
    set_kind("headeronly")
    add_includedirs("include")
    add_headerfiles("include/*.h")
    add_headerfiles("include/*.inl")
target_end()